// Regression diagnostics and performance measurements; Vue setup without a DOM.
// Run: node tests/stability.mjs
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { pathToFileURL, fileURLToPath } from 'node:url';
import { performance } from 'node:perf_hooks';
import { parse, compileScript } from '@vue/compiler-sfc';
import { nextTick, effectScope } from 'vue';
import { getScaleNotes, getDiatonicChords, SCALES } from '../src/core/scales.js';
import { getRootPositionMidi } from '../src/core/audio.js';
import { transposeNote, NOTE_TO_INDEX } from '../src/core/notes.js';
import { getChordDegree, applySuggestion } from '../src/core/suggestions.js';
const root = fileURLToPath(new URL('../', import.meta.url));
const source = fs.readFileSync(process.env.HG_SOURCE || path.join(root, 'src/App.vue'), 'utf8');
const { descriptor } = parse(source);
let compiled = compileScript(descriptor, { id: 'audit' }).content;
// Benchmark retained advanced engine separately from public FREE launch.
compiled = compiled.replace('const isFreeLaunch = true','const isFreeLaunch = false');
compiled = compiled.replace(/import (\w+) from '\.\/components\/[^']+\.vue'/g, (_, name) => `const ${name} = {}`);
 compiled = compiled.replace(/import logoUrl from '.\/assets\/logo.jpg'/, "const logoUrl = ''");
compiled = compiled.replace(/from '(\.\/core\/[^']+)'/g, (_, p) => `from '${pathToFileURL(path.resolve(root, 'src', p)).href}'`);
compiled = compiled.replace(/from 'vue'/g, `from '${pathToFileURL(path.join(root, 'node_modules/vue/dist/vue.runtime.esm-bundler.js')).href}'`);
const temp = path.join(os.tmpdir(), `harmonigrid-stability-${process.pid}.mjs`);
fs.writeFileSync(temp, compiled);
const { default: component } = await import(pathToFileURL(temp));
const warnings = [];
const originalWarn = console.warn;
console.warn = (...args) => warnings.push(String(args[0]));
const scope = effectScope();
const s = scope.run(() => component.setup({}, { expose() {} }));
const output = { environment: { node: process.version, platform: process.platform, mode: 'Vue setup in Node; no DOM/render/audio device' }, diagnostics: {} };
const d = output.diagnostics;
d.enharmonic = { scale: getScaleNotes('F#', 'major'), ESharpMidi: getRootPositionMidi({ root: 'E#', type: 'dim' }), transposeEsharp: transposeNote('E#', 2, 'G#') };
d.degreeQuality = { DmajorInC: getChordDegree('D', 'maj', 'C', 'major'), DminorInC: getChordDegree('D', 'min', 'C', 'major') };
d.alteredFifth = getRootPositionMidi({ root: 'C', type: '7', tensions: ['b5'] });
d.unknownSus = getRootPositionMidi({ root: 'C', type: '7sus4' });
d.unrecognizedGeneratedRoots = [];
for (const k of Object.keys(NOTE_TO_INDEX)) for (const [sc] of Object.entries(SCALES)) for (const c of getDiatonicChords(k, sc)) if (NOTE_TO_INDEX[c.root] === undefined) d.unrecognizedGeneratedRoots.push({ key: k, scale: sc, root: c.root });
s.setPlan('PRO'); s.configMeasuresCount.value = 4; s.startProject(); await nextTick();
s.measures.value[0].beats[0] = { id: 'beat-a', root: 'C', type: 'maj', bass: 'E', subdivisions: [{ id: 'sub-a', root: 'G', type: '7' }] };
await nextTick();
s.transposeTargetKey.value = 'D'; s.transposeTargetScale.value = 'major'; s.transposeMode.value = 'tonal'; s.transposeScope.value = 'all'; s.applyTranspose(); await nextTick();
d.transposeAll = JSON.parse(JSON.stringify(s.measures.value[0].beats[0]));
s.key.value = 'C'; s.scaleType.value = 'major'; s.measures.value[0].beats[0] = {root:'C',type:'maj'}; await nextTick();
s.transposeMode.value = 'modal'; s.applyTranspose(); await nextTick();
d.modalTransposeCtoD = { key: s.key.value, chord: s.measures.value[0].beats[0] };
d.slashDisplay = s.splitChordDisplay({root:'C',type:'69',bass:'E'});
s.configMeasuresCount.value = 4; s.startProject(); await nextTick();
s.measures.value[0].beats[0] = { id:'original', root:'C',type:'maj' }; await nextTick();
s.selectedRangeStart.value=0; s.selectedRangeEnd.value=0; s.copySelectedMeasures(); s.selectedRangeStart.value=1; s.selectedRangeEnd.value=1; s.pasteCopiedMeasures(); await nextTick();
d.copyIds = s.measures.value.slice(0,2).map(m=>m.beats[0].id);
d.suggestionOverwrite = applySuggestion([{beats:[{id:'anchored',root:'C',type:'maj',harmonicRhythm:'double',subdivisions:[{root:'G'}],mutedNotes:['E']}]}], [{measureIndex:0,beatIndex:0,chord:{root:'F',type:'maj'}}]);
d.rhythmDurations = {dottedQuarter: s.getRhythmFigureDuration('dotted-quarter',false), restWhole:s.getRhythmFigureDuration('rest-whole',false), actualWhole:s.getBeatSlotDuration({id:'x',beats:Array.from({length:4},()=>({root:'',type:''}))},{root:'C',harmonicRhythm:'rest-whole'},0)};
s.configMeasuresCount.value=21; s.startProject(); await nextTick(); s.setPlan('FREE'); await nextTick(); d.downgradeCount=s.measures.value.length;
output.benchmarks=[];
for (const n of [20,100,300,999]) {
  s.setPlan('PRO'); s.configMeasuresCount.value=n;
  let t=performance.now(); s.startProject(); await nextTick(); const createMs=performance.now()-t;
  for(let i=0;i<n;i++) s.measures.value[i].beats[0]={root:['C','G','A','F'][i%4],type:i%4===2?'min':'maj'};
  await nextTick();
  t=performance.now(); s.saveHistory(); const historyMs=performance.now()-t;
  t=performance.now(); s.measures.value[0].beats[0].type='maj7'; await nextTick(); const editFlushMs=performance.now()-t;
  t=performance.now(); s.updateSuggestionsPool(); const suggestionsMs=performance.now()-t;
  t=performance.now(); const systemsCount=s.systems.value.length; const systemsMs=performance.now()-t;
  output.benchmarks.push({measures:n,createMs,historyMs,editFlushMs,suggestionsMs,systemsMs,systemsCount,snapshotBytes:Buffer.byteLength(JSON.stringify(s.undoStack.value.at(-1)))});
}
scope.stop(); if(s.toastTimeout.value) clearTimeout(s.toastTimeout.value);
console.warn=originalWarn;
output.warningTypes=[...new Set(warnings)];
const outPath=path.join(root,process.env.HG_RESULTS || 'docs/stabilization/performance-after.json'); fs.writeFileSync(outPath, JSON.stringify(output,null,2));
console.log(JSON.stringify({...output,diagnostics:{...d,unrecognizedGeneratedRoots:{count:d.unrecognizedGeneratedRoots.length,examples:d.unrecognizedGeneratedRoots.slice(0,12)}}},null,2));
