import {createApp,ref,computed} from 'vue'
import CloudWorkspace from '../../src/components/CloudWorkspace.vue'
import {switchAccount,setOffline,changeRemote} from './mock-supabase.js'
import '../../src/style.css'
createApp({components:{CloudWorkspace},setup(){
 const make=()=>({format:'harmonigrid-project',schemaVersion:1,title:'Creación personal',key:'C',scaleType:'major',timeSignature:4,timeSignatureUnit:4,globalGrouping:[4],globalGroove:'Ninguno',globalShowObligado:false,globalShowSubdivisions:false,showLyricsGlobal:false,measures:[{id:'m1',beats:[{root:'C',type:'maj'},{root:'G',type:'maj'},{root:'A',type:'min'},{root:'F',type:'maj'}],lyrics:{rawText:'Mi canción',mode:'free'}}],repeats:[],tiedSlots:[],lyricsTiedSlots:[],preferences:{viewMode:'compact',notationMode:'chords',measuresPerSystem:4,bpm:120}})
 const document=ref(null),generation=ref(0)
 return{snapshot:computed(()=>document.value?JSON.parse(JSON.stringify(document.value)):null),document,generation,switchAccount,setOffline,changeRemote,newProject(){generation.value++;document.value=make()},clear(){document.value=null;generation.value++},load(value){document.value=value}}
},template:`<main><aside class="p-3 bg-amber-100"><strong>PRUEBA LOCAL: cuentas y servidor simulados</strong><div class="flex flex-wrap gap-2 mt-2"><button @click="switchAccount('A')">Cuenta de prueba A</button><button @click="switchAccount('B')">Cuenta de prueba B</button><button @click="newProject">Nueva creación de prueba</button><button @click="setOffline(true)">Simular desconexión</button><button @click="setOffline(false)">Restablecer conexión</button><button @click="changeRemote">Simular otro dispositivo</button></div></aside><CloudWorkspace :document="snapshot" :generation="generation" @load="load" @clear-account="clear"/><section class="p-4" v-if="document"><label>Título de prueba<input class="border p-3 block" v-model="document.title"/></label><p>Acordes conservados: {{document.measures[0].beats.map(b=>b.root+b.type).join(' · ')}}</p></section><p v-else class="p-4">Sin composición en el editor</p></main>`}).mount('#cloud-test')
