// src/core/notes.js

// Usaremos un sistema numérico de 12 tonos (0-11) donde 0 = C
export const CHROMATIC_NOTES_SHARP = ['C', 'C#', 'D', 'D#', 'E', 'F', 'F#', 'G', 'G#', 'A', 'A#', 'B']
export const CHROMATIC_NOTES_FLAT = ['C', 'Db', 'D', 'Eb', 'E', 'F', 'Gb', 'G', 'Ab', 'A', 'Bb', 'B']

// Include written enharmonics generated by the scale engine. All consumers
// (audio, transposition and analysis) must agree on their sounding pitch.
export const NOTE_TO_INDEX = Object.freeze(Object.assign(Object.create(null),
  ...Object.entries({C:0,D:2,E:4,F:5,G:7,A:9,B:11}).map(([letter,pitch]) => {
    const aliases = {[letter]:pitch}
    for(let amount=1;amount<=2;amount++) {
      aliases[letter+'#'.repeat(amount)] = (pitch+amount)%12
      aliases[letter+'b'.repeat(amount)] = (pitch-amount+12)%12
    }
    return aliases
  })))

// Para decidir si usar bemoles o sostenidos según la tónica
export const KEYS_WITH_SHARPS = ['C', 'G', 'D', 'A', 'E', 'B', 'F#', 'C#']
export const KEYS_WITH_FLATS = ['F', 'Bb', 'Eb', 'Ab', 'Db', 'Gb', 'Cb']

export function getNoteName(index, keyRoot = 'C') {
  // Aseguramos que el índice esté entre 0 y 11
  const normalizedIndex = ((index % 12) + 12) % 12
  
  if (KEYS_WITH_FLATS.includes(keyRoot)) {
    return CHROMATIC_NOTES_FLAT[normalizedIndex]
  }
  return CHROMATIC_NOTES_SHARP[normalizedIndex]
}

export function transposeNote(noteName, semitones, targetKeyRoot = 'C') {
  if (!noteName) return null
  const currentIndex = NOTE_TO_INDEX[noteName]
  if (currentIndex === undefined) return noteName
  
  return getNoteName(currentIndex + semitones, targetKeyRoot)
}
