-- Project wvkldhkgznersewjmhzo. Owner confirmed execution on 2026-10-04.
-- Fail rather than silently modify an existing table with different semantics.
begin;

create table public.harmonigrid_projects (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null default auth.uid() references auth.users(id) on delete restrict,
  title text not null check (char_length(btrim(title)) between 1 and 500),
  schema_version integer not null default 1 check (schema_version = 1),
  document jsonb not null,
  revision bigint not null default 1 check (revision between 1 and 9007199254740991),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint hg_document_object check (jsonb_typeof(document) = 'object'),
  constraint hg_document_size check (octet_length(document::text) <= 8388608),
  constraint hg_document_measures check (
    case when jsonb_typeof(document->'measures') = 'array'
      then jsonb_array_length(document->'measures') between 1 and 999
      else false end
  )
);

create index harmonigrid_projects_owner_updated_idx
  on public.harmonigrid_projects (owner_id, updated_at desc, id);

create function public.hg_project_revision_v1()
returns trigger language plpgsql security invoker set search_path = '' as $$
begin
  new.revision := old.revision + 1;
  new.updated_at := clock_timestamp();
  return new;
end;
$$;

create trigger harmonigrid_projects_revision
  before update on public.harmonigrid_projects
  for each row execute function public.hg_project_revision_v1();

alter table public.harmonigrid_projects enable row level security;
revoke all on public.harmonigrid_projects from public, anon, authenticated;
grant select on public.harmonigrid_projects to authenticated;
-- Owner, revision and timestamps are generated by the database, not the client.
grant insert (id, title, schema_version, document) on public.harmonigrid_projects to authenticated;
grant update (title, schema_version, document) on public.harmonigrid_projects to authenticated;
revoke all on function public.hg_project_revision_v1() from public, anon, authenticated;

create policy hg_projects_select_owner on public.harmonigrid_projects
  for select to authenticated using ((select auth.uid()) = owner_id);
create policy hg_projects_insert_owner on public.harmonigrid_projects
  for insert to authenticated with check ((select auth.uid()) = owner_id);
create policy hg_projects_update_owner on public.harmonigrid_projects
  for update to authenticated using ((select auth.uid()) = owner_id)
  with check ((select auth.uid()) = owner_id);

-- No anonymous access, public sharing or client deletion in this initial schema.
commit;
